version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .

# sphinx:
#   fail_on_warning: true

formats:
  - pdf
  - epub

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
